language: node_js
services:
- docker
cache:
  directories:
  - ~/.nvm
  - node_modules
notifications:
  slack: 
    rooms:
      - secure: "RJ/73DS8wqFbZwYBL/N5Zs+2b31z1TKYHuK/g4b+UO20R9z2N1ut0uEZlxkll56X4/MX4aDeHZIZnsaJjEDqMMs17lW1ZIwBcD+jfRvJVAoQvoQN9fBPneXSf72uUy7Nff4IZ0odkWOkgd0VGiKU/pq8bo53g3NT3VJiKSY/LOQs+YN8DNd/WqSEP7xKLZJnxO+IKIWUXjZGRp95G3qMy0H8ZFuFO8czhs0yd2QlxOCv3APPEtSYETi3oGwYM5Y/04TD1Hwzw/qDMBSHvtJpgS29pDNM2JQjTiQGPUGJo1O1wIgOaprlSBLhHTACIXwr2VhqQBK4cXL0r+mY7kFFbQAqdlwEFixELiuJF6D6eHQiJGj6jsOttvn2jyhW/nwo99312lJlQ3Jis3KIZ2CgTR82vmVqkKUr5MHbgSyQFCvVbk4yRQ9koDafJZc0chbkSaEg2HhMq1jl0S3f1yuKsTFE+/Hiw+ZQ1sAlaU8TsiotZIUoIIKLburIi90Stx0IOMSgR7IfLje9cKeR6RRZxGEPmPGVEtIhl4leNjRvLiMj6MCjR9d/IoUuFKcgHtcrNSs06OjnD2WVPMd4JSoM8prZQNhJtfwfB6bYRlm2v8Ti8/kF+HNpbK/u1JD/Qpg77qwEH76WtfZOaA1qm8tino/OrQVLyH6cOek08suDqgM="
    on_success: always
env:
  global:
  - RELEASE_BRANCH="master"
  - DOCKER_HUB_ACCOUNT="edenlabllc"
  - MAIN_BRANCHES="master develop"
  - secure: "Rv94miJjRf8qkkU2nqmLX27u8VKzRz03YsxgHmOJcQqfovGWlZ3cBopwKV7UiOk3EklsPRWXYMaV6UZBvKqeutFYvuWDO7hYqI9sxRnhf0iEUxGZkXf0bjIB64Y3s8xToothRCoccJMNuqIgDE/jEc/yfzoYeqGS3xx3SfduWIZ94H+Ug13TuYexMalWGNmVHHmCr3/V3mt5Kmao5PUUEP+I3TlI7OBMbMp/cBixbzF0w1nfuuH++uw/DUMf4HwjfD2cRiSZCW3KKGjjG3fxtnX1mcCZKh4Eb+zho1kcxjtl7NTqLwtrxgd8bXvB7Sh3yabFeP3t/IEadXrdP1gnAEL86ylADmcHINjujTAEXIUmsm7tUZHf4iRSTbrPh0BA6gLTks8ncPX12xI6qHma0O1MEmH3gbpay5Xw1CIP6547RqwhtyN0Zc2pH4Df0/sChzKncZy10o/0Cj+uo5jBnG2hHL+GPKxqfv1cinSjYzOfpDEBVp9S7t5/2QOz/gEmyK6XypwtnS3MXgM2dMlHhkhPQ6YnxrqrrrSK+FvIYqbFZhPT0NoWPBGiu0tqp7CPIDGBHGxp9Ek0NWEZ4lRZDpjoy5LOcK8layMDktQTaR2dvpU65mLTQIkq72Rxc0xzlktn0Pke1BNlxTIuS9FESaYQYfilLHNUhuxPjLa63X4="
  - secure: "A7HHteXxuWhR9YpcWqwvocU3fNkRsJXFFcCEsLidJg7EESuzt16baFu5cLF2px62G2Y89WfE82hOJYn11D7LrCcXXDWWIgH0lKacGVK5bv2IkuvYCtqqzAvPx3AcQXI0iuCriM1xMcoQts3iRg8M056USjsk8fhH1/0kXbd3N6DHCU5K0ePw5+EO2RTRz/1HPLx5ah0v+3xkeLaj9rC8Q3s7l0LsfasG2UcPyYcgCkoM2tEXaxq5mpxRin6Xh4VUB33H6weLN++nF/JUkyRzSHG4kmZxVJ1sFSrjQoVuj3bwj4hE/W68wcVD9fSYUQrCBFjyFNK0mg7RmJZ7PzixqBwFSoZmFNFm7kHj0SkeJBzNd89OKBMe2g7eY+cndT0BKMvIYk281PW4PpN+7duwaCViESxMBYjlPtuFFa1G9B05HLI2wD4nZuu5XZ6MTBXWnx+ke901RS000xDeuJBXfndqjJRP03HMkVef91tHCpOxwXHRCkohtyO2uAsvE9DR74kHc3+e9KwBZTPgyy9ioUE0vMPPrYK+YNh3hcLDKERRa4aAtdvI1aE4d2Ym8qj52wLbXeh4QP82vjzIfvIwS5fVRSJwZxPiprPdEKA9/OkeSvurebwjGP4RWoPspwziU9KbDWVxlVvH0G1WLyhHLz5ba7fyhwSKBFsjX7s60Fw="
node_js:
- 7.5.0
before_install:
- npm run docker:up
- chmod -R +x bin
script:
- npm run test
- npm run lint || travis_terminate 1
- ./bin/version-increment.sh || travis_terminate 1
- ./bin/build.sh || travis_terminate 1
- ./bin/start.sh || travis_terminate 1
- sleep 5
- docker ps
- RUNNING_CONTAINERS=`docker ps | wc -l`; if [ "${RUNNING_CONTAINERS//[[:space:]]/}"
  == "1" ]; then echo "[E] Container is not started\!"; docker logs man.web --details
  --since 5h; exit 1; fi;
- npm run nightwatch -- -e travis
- sleep 5
after_success:
- ./bin/ci/push.sh
-     openssl aes-256-cbc -K $encrypted_49e7c0de129f_key -iv $encrypted_49e7c0de129f_iv -in eHealth-8110bd102a69.json.enc -out eHealth-8110bd102a69.json -d
- sudo ./bin/deploy.sh || travis_terminate 1
